### ISSUE TITLE
[update] _image.scssを_align.scssに変更

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/gulp-ejs-sass#101]
現状では画像に限定しているけど、例えばボタンに使えたりもする。

``` scss
.u-image-center {
  display: block !important;
  margin: auto !important;
}

.u-image-right {
  display: block !important;
  margin: auto !important;
  margin-right: 0 !important;
}
```

`.u-image`ではなく、`.u-align`にした方が汎用的に使える。

``` scss
.u-align-center {
  display: block !important;
  margin-right: auto !important;
  margin-left: auto !important;
}

.u-align-right {
  display: block !important;
  margin-left: auto !important;
  margin-right: 0 !important;
}
```
