### ISSUE TITLE
[update] リストコンポーネントのテキストを左揃えに変更

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/gulp-ejs-sass#102]
``` scss
.c-list-unstyled__items > li {
    padding-left: 1em;
    text-indent: -1em;
}

li.c-list-ordered__item {
    position: relative;
    padding-left: 1em;
}

.c-list-ordered__item:before {
    position: absolute;
    left: 0;
}
```
