### ISSUE TITLE
[add] list-markコンポーネントの追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/gulp-ejs-sass#103]
左にアイコン、右にテキストが配置されるリストコンポーネントを追加。ひとまずmixinを作る（現段階でアイコンがない）。

`.c-list-ordered`をベースにする。

``` scss
/* ul */
.c-list-ordered {
  display: table;
  @include _c-list-unstyled();
}

/* ul > li */
.c-list-ordered__item {
  display: table-row;
  counter-increment: ordered;
}

.c-list-ordered__item:before {
  content: counters(ordered, ".") " ";
  display: table-cell;
  padding-right: 0.5em;
  text-align: right;
}

/* li > ul */
.c-list-ordered__items {
  counter-reset: ordered;
  @include _c-list-unstyled();
}
```
