### ISSUE TITLE
pxをremに変換するSassの関数を追加

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/gulp-ejs-sass#69]
remのベースフォントサイズはブレイクポイントと連動して変更できるようにしておく。例えば、

``` scss
$_font-size: (
  'sm': 15px,
  'md': 16px,
) !default;

@function _rem($px, $key: 'sm') {
  $value: map-get($_font-size, $key);
  @return ($px / $value) * 1rem;
}

html {
  font-size: map-get($_font-size, sm);
  @media (min-width: 768) {
    font-size: map-get($_font-size, md);
  }
}

.foo {
  font-size: _rem(15px);
  margin-bottom: _rem(30px);
  @media (min-width: 768px) {
    font-size: _rem(16px, md);
    margin-bottom: _rem(32px, md);
  }
}
```

変換後、

``` css
html {
  font-size: 15px;
}
@media (min-width: 768) {
  html {
    font-size: 16px;
  }
}

.foo {
  font-size: 1rem;
  margin-bottom: 2rem;
}
@media (min-width: 768px) {
  .foo {
    font-size: 1rem;
    margin-bottom: 2rem;
  }
}
```
