### ISSUE TITLE
[update] リストタグのデフォルトスタイルを検討する

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/gulp-ejs-sass#78]
`:not()`を使って、クラスの指定していない要素にはデフォルトスタイルをつけることができる。

``` scss
ul, ol {
  padding-left: 0;
  list-style-type: none;
}

ul:not([class]),
ol:not([class]) {
  padding-left: 1.5rem;
}

ul:not([class]) { list-style-type: disc; }
ol:not([class]) { list-style-type: decimal; }
```

もしScopeレイヤーでul要素にスタイルをつけたい場合でも、詳細度は同じ0,0,1,1になるので、上書きすることはできる。

ややこしくなる？単純に`.c-list-unstyled`を指定した方がマークアップか@mixinは必要だけど、わかりやすくはある。
