### ISSUE TITLE
[update] リストコンポーネントの要素セレクタをクラスセレクタに変更

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/gulp-ejs-sass#92]
`.c-list-unstyled`と`.c-list-ordered`の要素セレクタへの指定をやめる。スタイルを指定しているところはクラス指定をして詳細度を上げないようにする。

マークアップはやりにくくなるけど、上書きがつらくなりそう。

``` scss
.c-list-unstyled ul {
  list-style-position: inside;
}

// 修正後
.c-list-unstyled__items {
  list-style-position: inside;
}
```

``` scss
.c-list-ordered {
  @include _c-list-unstyled();
  counter-reset: ordered;
}

.c-list-ordered > li:before {
  counter-increment: ordered;
  content: counters(ordered, ".") " ";
  padding-right: 0.5em;
}

li > .c-list-ordered {
  padding-left: 1em;
}

// 修正後
.c-list-ordered {
  @include _c-list-unstyled();
  counter-reset: ordered;
}

.c-list-ordered__item:before {
  counter-increment: ordered;
  content: counters(ordered, ".") " ";
  padding-right: 0.5em;
}

.c-list-ordered__items {
  padding-left: 1em;
  list-style-type: none;
  counter-reset: ordered;
}
```
