### ISSUE TITLE
[fix] フルードイメージのSVG対応

### ISSUE THREAD

**Issue by manabuyasuda** [manabuyasuda/gulp-ejs-sass#94]
SVGを`<img>`要素と`<object>`でフルードイメージにする場合、IEで不具合が出る。以下のスタイルを追加する。

``` css
[src$=".svg"],
[data$=".svg"] {
  width: 100%; /* IE対応 */
}
```
